### ISSUE TITLE
Viewing angle jitter when viewing and playing back video after installing [altoclef][Replay Mod] at the same time.

### ISSUE THREAD

**Issue by BrGef** [adrisj7-AltoClef/altoclef-fabric-old#372]
## Steps to Reproduce (as best as you can)
gleichzeitig installiert[altclef][Replay Mod]
## Actual Behavior (What lead to the bot getting permanently stuck)
Viewing angle jitter of watching playback video

## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_

### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by JamesGreen31** [comment]
This is actually a baritone setting. Do # freelook off and it should fix it.
